---

- name: Generate mail filters
  hosts: localhost
  become: no
  gather_facts: no

  tasks:

    - name: include filters
      include_vars: "{{ lookup('first_found', possible_files) }}"
      vars:
        possible_files:
          - "filters.yml"
          - "encrypted-filters.yml"

    - name: build out template
      template:
        src: mailFilters.xml.j2
        dest: mailFilters.xml
