---

- name: Generate mail filters
  hosts: all
  connection: local
  become: no
  gather_facts: no

  tasks:

    - name: include filters
      include_vars: "{{ lookup('first_found', possible_files) }}"
      vars:
        possible_files:
          - "filters.yml"
          - "encrypted-filters.yml"

    - name: set author_name
      set_fact:
        author_name: Unknown Person
      when:
        - 'author_name is not defined'

    - name: set author_email
      set_fact:
        author_email: unknown@localhost
      when:
        - 'author_email is not defined'

    - name: build out template
      template:
        src: mailFilters.xml.j2
        dest: mailFilters.xml
